name: Build

on:
  push:
    branches:
      - '**'  # All branches on push
  pull_request:
    branches:
      - 'main'  # Only main branch on pull-request

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.5
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.5'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Initialize environment
      run: |
        make env
    - name: Run non-integration tests
      env:
        GROQ_API_KEY: ${{secrets.GROQ_API_KEY}}
        FRED_API_KEY: ${{secrets.FRED_API_KEY}}
      if: github.event_name == 'push'
      run: |
        make test-non-integration
    - name: Run integration tests + non-integration tests
      env:
        GROQ_API_KEY: ${{secrets.GROQ_API_KEY}}
        FRED_API_KEY: ${{secrets.FRED_API_KEY}}
      if: github.event_name == 'pull_request'
      run : |
        make test
    - name: Upload coverage reports to Codecov
      if: github.event_name == 'pull_request'
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
